# pylint: disable=all

from typing import ContextManager

def tempdir() -> ContextManager[str]: ...
def tempfile() -> ContextManager[str]: ...
def change_dir(path: str) -> ContextManager[None]: ...
def change_env(**env_vars: dict) -> ContextManager[None]: ...
