# pylint: disable=all

from functools import partial

def matches(regex: str, *strings: str) -> bool: ...
def ensure_matches(regex: str, *strings: str, msg: str = "") -> None: ...
def is_email(*strings: str) -> bool: ...
def is_ipv4(*strings: str) -> bool: ...
def is_ipv6(*strings: str) -> bool: ...
def is_ip(*strings: str) -> bool: ...
